[PriorityMod]
enabled = true

## Priorities
# No Change     = -1
# Idle          = 0
# Below Normal  = 1
# Normal        = 2
# Above Normal  = 3
# High          = 4
# Realtime      = 5     (Run as Administrator is required) (Not Recommended)
# Check Microsoft official document for the details
# https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass#parameters
priority = 4

## Affinity
# Process Affinity (0 = no change)
# Check Microsoft official document for the details
# https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups

# To set the value. You need CPU Affinity Mask Calculator
# https://bitsum.com/tools/cpu-affinity-calculator/
affinity = 0

## Dynamic Priority
# Priority and affinity will set to value below when lost focus
# Regain focus or not responding will set back to [PriorityMod] section
[DynamicPriority]
enabled = false
idle_priority = 1
idle_affinity = 0